version: '3'

services:
  victim:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app:rw

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8081
      - 50000:50000
    volumes:
      - .:/code:ro
    environment:
      - JENKINS_OPTS="--httpPort=8081"
