version: '3.7'

services:
  
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-java
  #   ports:
  #     - "8080:8080"
  
  spa:
    build:
      context: .
      dockerfile: Dockerfile-spa
    ports:
      - "4200:4200"

