version: '3'

services:
  victim:
    build: .
    ports:
      - 8090:8090
    volumes:
      - .:/app:rw

  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8081:8081
      - 50000:50000
    volumes:
      - ./:/code
    environment:
      - JENKINS_OPTS="--httpPort=8081"
