<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="es">
<!-- this template was designed by http://www.tristarwebdesign.co.uk - please visit for more templates & information - thank you. -->
<head>
<title>Fans de los bellos paisajes (CLCERT SWSEC Intro)</title>
<meta charset="utf-8" />
<link rel="stylesheet" type="text/css" href="css/style.css" />
</head>
<body>

<div id="border">
	<div id="container">
		
		<div id="menu">
			<ul>
				<li><a title="Home" href="index.jsp">Home</a></li><li>|</li>
				<li><a title="Ingresar" href="login.jsp">Ingresar</a></li><li>|</li>
				<li><a title="Muro" href="Wall">Muro</a></li><li>|</li>
				<li><a title="Saludos" href="saludos.jsp">Saludos</a></li><li>|</li>
				<li><a title="Usuarios" href="ListaUsuarios?type=1">Usuarios</a></li><li>|</li>
				<li><a title="Salir" href="Exit">Salir</a></li>
			</ul>
		</div>
	
		<div id="header">
			<p><a title="website name" href="index.jsp">Fans de los bellos paisajes</a></p>
		</div>
		
		<div id="content">
