<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<!-- this template was designed by http://www.tristarwebdesign.co.uk - please visit for more templates & information - thank you. -->
<head>
<title>Fans de los bellos paisajes (CLCERT SWSEC Intro)</title> <!-- change to whatever you want as the title for your website -->
<meta name="description" content=" " /> <!-- enter a description for your website inside the " " -->
<meta name="keywords" content=" " /> <!-- enter a a string of keywords that relate to your website inside the " " -->
<meta http-equiv="Content-Language" content="en-gb" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<link rel="stylesheet" type="text/css" href="css/style.css" />
</head>
<body>

<div id="border">
	<div id="container">
		
		<div id="menu">
			<ul>
				<li><a title="Home" href="index.jsp">Home</a></li><li>|</li>
				<li><a title="Ingresar" href="login.jsp">Ingresar</a></li><li>|</li>
				<li><a title="Muro" href="Wall">Muro</a></li><li>|</li>
				<li><a title="Saludos" href="saludos.jsp">Saludos</a></li><li>|</li>
				<li><a title="Salir" href="Exit">Salir</a></li>
			</ul>
		</div>
	
		<div id="header">
			<p><a title="website name" href="index.jsp">Fans de los bellos paisajes</a></p>
		</div>
		
		<div id="content">
